ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Controllers/EntitleController.cs
using System.Web.Mvc;

namespace ISSSTE.TramitesDigitales2015.Turissste.Presentacion.Controllers
{
    public class EntitleController : Controller
    {
        public ActionResult Index(string noIssste)
        {
            return View();
        }
    }
}

ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Views/Entitle/Index.cshtml
@{
    ViewBag.Title = "Solicitud de servicios turísticos";
    Layout = "~/Views/Shared/_LayoutTurissste.cshtml";
}

<link href="~/Content/EntitleCss/EntitleIndex.css" rel="stylesheet" />

<div class="container" ng-controller="MainController">
    <div class="row">
        <div class="col-md-7">
            <ol class="breadcrumb">
                <li>
                    <a href="http://www.gob.mx"><i class="icon icon-home"> </i></a>
                    <i id="navinicio" class="active"><a href=@Url.Action("Index","Entitle")></a></i>
                </li>
                <li id="navinicio"><a href=@Url.Action("Index", "Entitle")>Inicio</a></li>
            </ol>
        </div>
        <div class="container setMiddle col-md-4 col-md-offset-1">
            <div><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{derechohabiente.NombreCompleto}} <a class="pull-right LinkWithoutLine" href="https://oficinavirtual.issste.gob.mx/accesogobmx/ctl/logoff.aspx">Salir</a> </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <img src="~/Imagenes/LayoutPeticiones/svg-pegado-787991x237.svg" width="120" />
        </div>
        <div class="col-md-2 col-md-offset-6">
            <img class="pull-right" src="~/Imagenes/LayoutPeticiones/LOGO_ISSSTE.svg.png" width="120" />
        </div>
    </div>
    <div class="row bottom-buffer unselectableText">
        <h1 class="col-md-8">Solicitud de servicios turísticos</h1>
    </div>
    <div class="unselectableText">
        <ul class="nav nav-tabs col-md-8">
            <li class="ei_fingerpoint" ng-click="makeTabActive('01')">
                <a data-toggle="tab" data-target="#tab-01"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Descripción </a>
            </li>
            <li class="ei_fingerpoint" ng-click="makeTabActive('02')">
                <a data-toggle="tab" data-target="#tab-02"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Acerca del trámite</a>
            </li>
            <li class="ei_fingerpoint" ng-click="makeTabActive('03')">
                <a data-toggle="tab" data-target="#tab-03"><span class="glyphicon glyphicon-inbox" aria-hidden="true"></span> Requisitos del trámite</a>
            </li>
        </ul>
    </div>
    <div class="tab-content col-md-8 bottom-buffer unselectableText">
        <div class="tab-pane" id="tab-01" ng-class="tab01Class">
            <div>
                <span class="text-justify">
                    <h5>Nombre de la modalidad</h5>
                    <span>Información, reservación y venta de servicios de hospedaje, transportación terrestre, aérea y paquetes turísticos a los derechohabientes</span><br /><br />
                    <h5>¿Para qué te sirve este trámite?</h5>
                    <span>Para la reservación y adquisición de servicios turísticos, como hospedaje, transportación terrestre y/o aérea y paquetes turísticos a cualquier destino nacional o internacional.</span><br /><br />
                    <h5>Estimado derechohabiente:</h5>
                    <span>Es importante que proporciones tus datos de contacto para cualquier duda o aclaración con respecto a tu trámite. Estos datos personales son considerados como confidenciales y estarán protegidos conforme a la Ley Federal de Transparencia y Acceso a la Información Pública Gubernamental.</span><br /><br />
                </span>
            </div>
        </div>
        <div class="tab-pane" id="tab-02" ng-class="tab02Class">
            <div>
                <p>
                    <span class="text-justify">
                        <h5>¿Quién puede realizar el trámite?</h5>
                        <span>El interesado.</span><br /><br />
                        <h5>¿Cuál es el costo de este trámite?</h5>
                        <span>Trámite gratuito.</span><br /><br />
                        <h5>¿Qué pasos debo realizar para el trámite?</h5>
                        <span>
                            El trámite se realiza de manera presencial.
                            <br /><br />
                            1.	Acude a la Agencia de tu preferencia.<br />
                            2.	Solicita información y elige el servicio turístico de tu interés.<br />
                            3.	Indica su forma de pago.<br />
                            4.	Paga el servicio turístico solicitado.<br />
                            5.	Recibe documentos que comprueban el servicio solicitado, así como su pago.<br />
                            6.  Disfruta de tu viaje de acuerdo a las fechas solicitadas.<br />
                            <br />
                        </span>
                        <h5>¿En cuánto tiempo obtengo una respuesta de resolución de este trámite?</h5>
                        <span>Inmediato.</span>
                    </span>
                </p>
            </div>
        </div>
        <div class="tab-pane" id="tab-03" ng-class="tab03Class">
            <div>
                <p>
                    <span class="text-justify">
                        <span>
                            <h5>¿Qué documentos necesito y cuáles deben ser sus características?</h5>
                            1.	Identificación oficial vigente (Credencial para votar INE, Pasaporte o Cédula profesional). Original y copia.<br />
                            2.	Último recibo de nómina. Original.<br />
                            3.  Credencial de la dependencia donde laboras o, en su caso, credencial de jubilado. Original.<br /><br />
                        </span>
                    </span>
                </p>
            </div>
        </div>
    </div>
    <div id="alertPanel">
        <div id="infoPanel" style="text-align: center" class="alert alert-success alert-dismissible col-md-12" ng-if="InfoMessage.entitleSuccessMsg !== undefined">
            <div style="color: black !important">{{InfoMessage.entitleSuccessMsg}}</div>
        </div>
        <div id="errorPanel" style="text-align: center" class="alert alert alert-danger alert-dismissible col-md-12" ng-if="InfoMessage.entitleErrorMsg !== undefined">
            <div style="color: black !important">{{InfoMessage.entitleErrorMsg}}</div>
        </div>
        <div class="row">
            <h3 class="col-md-12">Datos del derechohabiente</h3>
        </div>
        <div class="row">
            <div class="col-md-12">
                <span style="width: 35px; height: 6px; background-color: #D0021B !important; position: absolute"></span>
                <hr style="position:relative; margin-top: 0px; margin-bottom: 65px;" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label class="control-label" for="txtRightholderFullname">Nombre(s):</label>
                <input type="text" id="txtRightholderFullname" class="form-control" ng-model="derechohabiente.Nombre" readonly="readonly" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label" for="txtRightholderFullname">Primer apellido:</label>
                <input type="text" id="txtRightholderFullname" class="form-control" ng-model="derechohabiente.ApellidoPaterno" readonly="readonly" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label" for="txtRightholderFullname">Segundo apellido:</label>
                <input type="text" id="txtRightholderFullname" class="form-control" ng-model="derechohabiente.ApellidoMaterno" readonly="readonly" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-2">
                <label class="control-label" for="txtRightholderAge">Edad:</label>
                <input type="text" id="txtRightholderAge" class="form-control" ng-model="derechohabiente.Edad" readonly="readonly" />
            </div>
            <div class="form-group col-md-2">
                <label class="control-label" for="txtRightholderGender">Sexo:</label>
                <input type="text" id="txtRightholderGender" class="form-control" ng-model="derechohabiente.Genero" readonly="readonly" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label" for="txtRightholderType">Derechohabiente:</label>
                <input type="text" id="txtRightholderType" class="form-control" ng-model="derechohabiente.TipoDerechohabiente" readonly="readonly" />
            </div>
            <div class="form-group col-md-4">
                <label class="control-label" for="txtRightholderAfiliation">Afiliacion:</label>
                <input type="text" id="txtRightholderAfiliation" class="form-control" ng-model="derechohabiente.Afiliacion" readonly="readonly" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label class="control-label" for="txtRightholderLocation">Localidad:</label>
                <input type="text" id="txtRightholderLocation" class="form-control" ng-model="derechohabiente.Estado" readonly />
            </div>
        </div>
        <br />
        <div class="row">
            <h3 class="col-md-12">Datos de contacto</h3>
        </div>
        <div class="row">
            <div class="col-md-12">
                <span style="width: 35px; height: 6px; background-color: #D0021B !important; position: absolute"></span>
                <hr style="position:relative; margin-top: 0px; margin-bottom: 65px;" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-1">
                <label class="control-label" for="txtRightholderLada">Lada<span ng-class="{asteriskError: entitleContactForm.txtRightholderLada.$invalid && entitleContactForm.txtRightholderLada.$dirty }"></span>:</label>
                <input type="text" id="txtRightholderLada" name="txtRightholderLada" class="form-control" ng-model="lada" maxlength="3" ng-maxlength="3" input-numero required autocomplete="off"
                       ng-class="{redBorderError: entitleContactForm.txtRightholderLada.$invalid && entitleContactForm.txtRightholderLada.$dirty}" ng-change="getContactInformation()" />

            </div>
            <div class="form-group col-md-3">
                <label class="control-label" for="txtRightholderTel">Teléfono<span ng-class="{asteriskError: entitleContactForm.txtRightholderTel.$invalid && entitleContactForm.txtRightholderTel.$dirty }"></span>:</label>
                <input type="text" id="txtRightholderTel" name="txtRightholderTel" class="form-control" ng-model="phoneNumber" maxlength="10" ng-maxlength="10" input-numero required autocomplete="off"
                       ng-class="{redBorderError: entitleContactForm.txtRightholderTel.$invalid && entitleContactForm.txtRightholderTel.$dirty}" ng-change="getContactInformation()" />

            </div>
            <div ng-class="regexIsValid ? 'form-group col-md-4' : 'form-group has-error col-md-4'">
                <label class="control-label" for="txtRightholderEmail">Correo electrónico<span ng-class="{asteriskError: entitleContactForm.txtRightholderEmail.$invalid && entitleContactForm.txtRightholderEmail.$dirty }"></span>:</label>
                <input type="text" id="txtRightholderEmail" name="txtRightholderEmail" class="form-control " ng-model="mail" placeholder="ejemplo@dominio.com" ng-maxlength="50" input-email required autocomplete="off"
                       ng-change="getContactInformation()" />
                <span class="tabValidation">*</span>
                <span class="angularMsgError" ng-if="!regexIsValid">
                    <span>El formato del correo es incorrecto</span>
                </span>
            </div>
            <div class="form-check col-md-4">
                <label class="control-label"></label>
                <label class="control-label">
                    <input type="checkbox" ng-model="isReceiveInformation" ng-change="getContactInformation()" />   Deseo recibir más información turística.
                </label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 setMiddle" style="color:#777; ">
            </div>
            <div class="col-md-6 col-md-offset-2">
                <div class="btn-group pull-right" role="group" aria-label="...">
                    <button class="btn btn-primary" id="rightHolderSaveContact" ng-if="derechohabiente.IdDerechohabiente != null" ng-click="updateContactInformation(derechohabiente)" ng-disabled="!regexIsValid">Actualizar datos</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container bottom-buffer">
    <div class="row">
        <div class="col-md-12" ng-view></div>
    </div>
</div>
<script type="text/ng-template" id="mensajes-error">
    <span ng-message="required">Este campo es obligatorio.</span>
    <span ng-message="minlength">Este campo es muy corto.</span>
    <span ng-message="maxlength">Este campo es muy largo.</span>
    <span ng-message="email">El formato no es válido.</span>
    <span ng-message="pattern">El formato no es correcto.</span>
</script>