ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Controllers/AdministratorController.cs
using System.Web.Mvc;

namespace ISSSTE.TramitesDigitales2015.PeticionesWeb.Presentacion.Controllers
{
    [Authorize]
    public class AdministratorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Views/Shared/_LayoutAdminTurissste.cshtml
@using ISSSTE.Tramites2015.Common.Security.Helpers
@{
    ViewBag.Title = "TURISSSTE";
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Images/Administrator/favicon.ico")" type="image/x-icon" />
    @Styles.Render("~/bundles/administrator/css")
    @Styles.Render("~/bundles/DatePicker")
</head>
<body> 
    <header>
        <div class="container-fluid abl-logoheader">
            <div class="row">
                <img class="logo" src="@Url.Content("~/Images/Administrator/issste-logo.jpg")">
            </div>
        </div>
        <div class="navbar navbar-default abl-navbar" role="navigation">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#side-menu" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="container-fluid">
                <div>
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="@Url.Action("Index", "Administrator", null, Request.Url.Scheme)">
                                @ViewBag.Title
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-user">
                        @if (Request.GetOwinContext().Authentication.User.Identity.IsAuthenticated)
                        {
                                var user = Request.GetOwinContext().GetAuthenticatedUser();
                                var displayName = (String.IsNullOrEmpty(user.Name) ? user.UserName : user.Name).Trim();
                                var userRole = user.Roles[0].Name;
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" style="cursor: pointer;">
                                    <span class="glyphicon glyphicon-user abl-usuarios" aria-hidden="true"></span>
                                    @displayName <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu multi-level">
                                    <li><a href="@Url.Action("Logout", "Account", new { returnUrl = Url.Action("Index", "Administrator", null, Request.Url.Scheme) }, null)">Cerrar sesión</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </header>
    <main>

    <div ng-app="ISSSTE.TramitesDigitales2015.Turissste.App">   
        @*<input type="hidden" id="baseUrl" value="@String.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))" />*@
        @RenderBody()
    </div>

    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/administrator/app")
    @*@Scripts.Render("~/bundles/angular-auto-validate")*@
    @RenderSection("scripts", required: false)
</body>
</html>

ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Views/Shared/_LayoutAdministrator.cshtml
@using ISSSTE.Tramites2015.Common.Security.Helpers
@{
    ViewBag.Title = "Trámites Digitales 2016";
}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Images/Administrator/favicon.ico")" type="image/x-icon" />
    @Styles.Render("~/bundles/administrator/css")
</head>
<body>
    <header>
        <!--/ START LOGO -->
        <div class="container-fluid abl-logoheader">
            <div class="row">
                <img class="logo" src="@Url.Content("~/Images/Administrator/issste-logo.jpg")">

                <div class="over">
                    &nbsp;
                    <span class="version">Versión 2.1</span>
                </div>
            </div>
        </div>
        <!--/ END LOGO


        <!--/ START NAV -->
        <div class="navbar navbar-default abl-navbar" role="navigation">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#side-menu" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="container-fluid">
                <div>
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="@Url.Action("Index", "Administrator", null, Request.Url.Scheme)">
                                @ViewBag.Title
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-user">
                        @if (Request.GetOwinContext().Authentication.User.Identity.IsAuthenticated)
                        {
                            <li>
                                @{
                                    var user = Request.GetOwinContext().GetAuthenticatedUser();

                                    var displayName = String.IsNullOrEmpty(user.Name) ? user.UserName : user.Name;
                                }
                                <a class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-user abl-usuarios" aria-hidden="true"></span> @displayName <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu multi-level">
                                    <li><a href="@Url.Action("Logout", "Account", new { returnUrl = Url.Action("Index", "Administrator", null, Request.Url.Scheme) }, null)">Cerrar sesión</a></li>
                                </ul>
                            </li>
                         }
                    </ul>
                </div>
            </div>
        </div>

    </header>
    <main>

        <div ng-app="ISSSTE.TramitesDigitales2015.Turissste.App">
            <input type="hidden" id="baseUrl" value="@String.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))" />
            @RenderBody()
        </div>

    </main>

    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angular-auto-validate")
    @Scripts.Render("~/bundles/angular-upload")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    @Scripts.Render("~/bundles/administrator/app")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/ramda")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/respond")
    @Scripts.Render("~/bundles/utils")
    @RenderSection("scripts", required: false)
</body>
</html>

ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Views/Shared/_LayoutEmpty.cshtml
@model ISSSTE.TramitesDigitales2015.Turissste.Presentacion.Models.LoginCompleteViewModel
@{
    ViewBag.Title = "Inicio de sesión exitoso";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-ng-app="ISSSTE.TramitesDigitales2015.Turissste.App">
        <input type="hidden" id="baseUrl" value="@String.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))" />
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/respond")
    @Scripts.Render("~/bundles/utils")
    @Scripts.Render("~/bundles/administrator/javascript")

    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angular-auto-validate")
    @Scripts.Render("~/bundles/angular-upload")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    @RenderSection("scripts", required: false)
</body>
</html>

ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Views/Shared/_LayoutRequest.cshtml
<!DOCTYPE html>
<html ng-app="requestForm">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link href="~/Content/favicons/favicon.ico" rel="shortcut icon" />
    <link href="https://framework-gb.cdn.gob.mx/qa/assets/styles/main.css" rel="stylesheet" />
    @Styles.Render("~/request-form/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Begin Digital Analytix Tag 1.1302.13 -->
    <script type="text/javascript">
	function udm_(e){var t="comScore=",n=document,r=n.cookie,i="",s="indexOf",o="substring",u="length",a=2048,f,l="&ns_",c="&",h,p,d,v,m=window,g=m.encodeURIComponent||escape;if(r[s](t)+1)for(d=0,p=r.split(";"),v=p[u];d<v;d++)h=p[d][s](t),h+1&&(i=c+unescape(p[d][o](h+t[u])));e+=l+"_t="+ +(new Date)+l+"c="+(n.characterSet||n.defaultCharset||"")+"&c8="+g(n.title)+i+"&c7="+g(n.URL)+"&c9="+g(n.referrer),e[u]>a&&e[s](c)>0&&(f=e[o](0,a-8).lastIndexOf(c),e=(e[o](0,f)+l+"cut="+g(e[o](f+1)))[o](0,a)),n.images?(h=new Image,m.ns_p||(ns_p=h),h.src=e):n.write("<","p","><",'img src="',e,'" height="1" width="1" alt="*"',"><","/p",">")};
	function uid_call(a, b){
		ui_c2 = 17183199; // your corporate c2 client value
		ui_ns_site = 'gobmx'; // your sites identifier
		window.b_ui_event = window.c_ui_event != null ? window.c_ui_event:"",window.c_ui_event = a;
		var ui_pixel_url = 'https://sb.scorecardresearch.com/p?c1=2&c2='+ui_c2+'&ns_site='+ui_ns_site+'&name='+a+'&ns_type=hidden&type=hidden&ns_ui_type='+b;
		var b="comScore=",c=document,d=c.cookie,e="",f="indexOf",g="substring",h="length",i=2048,j,k="&ns_",l="&",m,n,o,p,q=window,r=q.encodeURIComponent||escape;if(d[f](b)+1)for(o=0,n=d.split(";"),p=n[h];o<p;o++)m=n[o][f](b),m+1&&(e=l+unescape(n[o][g](m+b[h])));ui_pixel_url+=k+"_t="+ +(new Date)+k+"c="+(c.characterSet||c.defaultCharset||"")+"&c8="+r(c.title)+e+"&c7="+r(c.URL)+"&c9="+r(c.referrer)+"&b_ui_event="+b_ui_event+"&c_ui_event="+c_ui_event,ui_pixel_url[h]>i&&ui_pixel_url[f](l)>0&&(j=ui_pixel_url[g](0,i-8).lastIndexOf(l),ui_pixel_url=(ui_pixel_url[g](0,j)+k+"cut="+r(ui_pixel_url[g](j+1)))[g](0,i)),c.images?(m=new Image,q.ns_p||(ns_p=m),m.src=ui_pixel_url):c.write("<p><img src='",ui_pixel_url,"' height='1' width='1' alt='*'></p>");
	}
	udm_('https://sb.scorecardresearch.com/b?c1=2&c2=17183199&ns_site=gobmx&name=ISSSTE.PeticionesWeb.Peticiones');
    </script>
    <noscript><p><img src="https://sb.scorecardresearch.com/p?c1=2&amp;c2=17183199&amp;ns_site=gobmx&amp;name=ISSSTE.PeticionesWeb.Peticiones" height="1" width="1" alt="*"></p></noscript>
    <!-- End Digital Analytix Tag 1.1302.13 -->

</head>
<body>
    <main class="page">
        @RenderBody()
    </main>
    <script src="~/Scripts/request-form/Form.js"></script>
    <script src="https://framework-gb.cdn.gob.mx/qa/gobmx.js"></script>
    <script src="https://framework-gb.cdn.gob.mx/data/encuesta_v1.0/qa/encuestas.js"></script>
    @Scripts.Render("~/bundles/angularjs")
    @Scripts.Render("~/bundles/request-form")
    <script src="https://framework-gb.cdn.gob.mx/assets/scripts/jquery-ui-datepicker.js"></script>
    <script src='https://www.google.com/recaptcha/api.js' type="text/javascript"></script> 
    <!-- Begin DAx cs.js import -->
    <script type="text/javascript" src="https://sb.scorecardresearch.com/c2/17183199/ct.js"></script>
    <!-- End DAx cs.js import -->

</body>
</html>

ISSSTE.TramitesDigitales2016.PeticionesWeb.Presentacion/Views/Shared/_LayoutTurissste.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link href="~/Content/favicons/favicon.ico" rel="shortcut icon" />
    <link href="https://framework-gb.cdn.gob.mx/assets/styles/main.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="page" ng-app="TurisssteApp">
        @RenderBody()
    </div>
    <script src="https://framework-gb.cdn.gob.mx/assets/scripts/vendor/modernizr.js"></script>
    <script src="https://framework-gb.cdn.gob.mx/gobmx.js"></script>    
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/entitle/angular")
    <script src="https://framework-gb.cdn.gob.mx/assets/scripts/jquery-ui-datepicker.js"></script>
    <script src="https://framework-gb.cdn.gob.mx/data/encuesta_v1.0/qa/encuestas.js"></script>
</body>
</html>